backend/app/__init__.py
from flask import Flask
# from app.main import bp as main_bp
from config import Config
import os

def create_app(config_class=Config):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)

    # load the instance config, if it exists, when not testing
    app.config.from_object(config_class)

    # Initialize Flask extensions here

    # Register blueprints here
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    return app

backend/app/main/__init__.py
from flask import Blueprint
import logging

from config import Config


logging.basicConfig(level=Config.LOG_LEVEL)

bp = Blueprint("main", __name__)

from app.main import routes

backend/app/main/routes.py
import logging

import requests
from app.main import bp
import json
from flask import (
    Response,
    jsonify,
    redirect,
    render_template,
    request,
    send_file,
)
from flask_cors import cross_origin

from config import Config

log = logging.getLogger(__name__)

from app.main.video import decode_stream_url, stop_video, video_feed


# Produces the <img/> stream
@bp.route("/stream", methods=["GET"])
@cross_origin()
def stream():
    """Returns a stream of JPG images from a source. Takes a base64 encoded URL as a query parameter."""
    url_param = request.args.get("url")
    if url_param is None or url_param == "":
        return send_file("static/no-feed.jpg", mimetype="image/jpeg")
    else:
        url = decode_stream_url(url_param)
        return Response(
            video_feed(url), mimetype="multipart/x-mixed-replace; boundary=frame"
        )


# Creates a URL to stream back as JPG
@bp.route("/start", methods=["POST", "OPTIONS"])
@cross_origin()
def start_feed():
    content_type = request.headers.get("Content-Type")
    if request.method == "OPTIONS":
        response.headers.add("Access-Control-Allow-Origin", "*")
        return response

    if content_type == "application/json":
        data = json.loads(request.data)
        url = data["url"]
        response = jsonify({"rtsp": url})
        return response
    else:
        return "Content-Type not supported!"


# Stops the video
@bp.route("/stop", methods=["GET"])
@cross_origin()
def stop_feed():
    log.info("Stopping Feed")

    stop_video()

    return redirect("/", code=302)


# Home page
@bp.route("/", methods=["GET"])
def index():
    log.info(
        "Checking internet connectivity setting: {}".format(Config.SHOW_INTERNET_STATUS)
    )
    return render_template(
        "index.html",
        show_internet=Config.SHOW_INTERNET_STATUS,
        page_title=Config.PAGE_TITLE,
        display_model_name=Config.DISPLAYED_MODEL_NAME,
        default_stream_url=Config.DEFAULT_STREAM_URL,
        splash_image=Config.SPLASH_IMAGE,
    )


@bp.route("/favicon.ico")
def favicon():
    return send_file("static/favicon.ico", mimetype="image/vnd.microsoft.icon")


@bp.route("/internet-status", methods=["GET"])
@cross_origin()
def internet_status():
    try:
        result = requests.get("https://google.com", timeout=1)
        return str(result.status_code == 200)
    except requests.exceptions.RequestException as e:
        return "500"

backend/app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
      tailwind.config = {
        theme: {
          extend: {
            colors: {
              clifford: "#da373d",
            },
          },
        },
      };
    </script>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
  </head>
  <body class="m-4">

    {% block content %} {% endblock %}

  </body>
  </html>

backend/app/templates/index.html
{% extends 'base.html' %} {% block content %}

<h1 class="text-green-500 text-4xl font-bold">{{ page_title }}</h1>
<strong>{{ display_model_name }}</strong>
<div class="flex flex-row">
  <div class="basis-11/12">
    <img
      id="video"
      width="100%"
      height="100%"
      src="{{ url_for('static', filename=splash_image) }}"
    />
  </div>
  {% if show_internet == "true": %}
    <div class="basis-1/12 h-full object-none object-center ">
      <img
        id="internet-status"
        class="bg-yellow-300"
        style="background-color: green;" id="internet-status-background"
        src="{{ url_for('static', filename='interent-open-small.png') }}"
        />
    </div>
  {% else %}
    <div class="basis-1/12">
      &nbsp;
    </div>
  {% endif %}
</div>
<div class="flex flex-row">
  <div class="basis-11/12">
    Setup Info:
    <form name="rtsp-form" id="rtsp-form" action="#">
      <label for="rstp-url">
        <input
          type="text"
          name="rtsp-url"
          id="rtsp-url"
          value="{{ default_stream_url }}"
          placeholder="{{ default_stream_url }}"
        />
      </label>
      <input type="submit" name="rtsp-submit" id="rtsp-submit" value="Start" />
    </form>
    <a href="{{ url_for('main.stop_feed') }}">Reset</a>
  </div>
</div>

{% block javascript %}
<script>
  var URL_BASE = "{{ url_for('main.stream') }}";
  var INTERNET_BASE = "{{ url_for('main.internet_status') }}";
  rstpForm = document.getElementById("rtsp-form");

  document.getElementById("rtsp-submit").onclick = function () {
    // Submit button pressed, get the value, convert to base64 and replace the image
    url = document.getElementById("rtsp-url");
    if (url) {
      value = url.value.trim();
      if (value == "") {
        alert("RTSP URL is not valid");
      } else {
        updateStream(value);
      }
    }

    return false; // do not submit the form
  };

  function updateStream(target_url) {
    video = document.getElementById("video");
    encodedString = btoa(target_url);

    final_url = URL_BASE + "?url=" + encodedString;

    console.log("Final URL: " + final_url);
    video.src = final_url;
  }

  async function setInternetStatus(status) {
    var interentImage = document.getElementById("internet-status");
    value = await status;
    if (value == "True") {
      document.getElementById("internet-status-background").style.backgroundColor = "green";
      interentImage.src = "{{ url_for('static', filename='interent-open-small.png') }}";

    } else {
      document.getElementById("internet-status-background").style.backgroundColor = "red";
      interentImage.src = "{{ url_for('static', filename='interent-off-small.png') }}";
    }
  }

  //{% if show_internet == "true": %}
  setInterval(function () {
    fetch(INTERNET_BASE).then((response) => {
      setInternetStatus(response.text());
    });
  }, 2000);
  //{% endif %}

  // url = document.getElementById("rtsp-url");
  // if (url) {
  //   value = url.value.trim();
  //   if (value != "") {
  //     updateStream(value);
  //   }
  // }
</script>
{% endblock %}

{% endblock %}